# hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: telemedicine-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telemedicine-api
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10